fix(cors): #7 issue with cross origin support (#8)
* refactor(fix getPort)

Fix error when option -p is passed,
setup expect always a promise, so it fails when port is a number:

exprexo -d routes/ -p 3000
exprexo and javascript make the perfect blend
/home/user/.nvm/versions/node/v6.3.0/lib/node_modules/exprexo/lib/cli/index.js:12
.then(updateOptions)
^

TypeError: getPort(...).then is not a function
at setup (/home/user/.nvm/versions/node/v6.3.0/lib/node_modules/exprexo/lib/cli/index.js:12:6)
at Object.<anonymous> (/home/user/.nvm/versions/node/v6.3.0/lib/node_modules/exprexo/bin/exprexo:16:1)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.runMain (module.js:575:10)
at run (bootstrap_node.js:352:7)
at startup (bootstrap_node.js:144:9)

* add quickSetup.gif

* docs( add quickSetup gif )

* docs(change what is)

* chore(cors): Remove corses, use cors for cross origin

* fix(crossOrigin): use cors

fix #7